#define SERIAL_NUMBER "917a595fba5dba86"
// #define SECRET_SSID "BenjiPhone"
// #define SECRET_PASS "beomjaemin"
// #define SECRET_SSID "IllinoisNet_Guest"
// #define SECRET_PASS ""
#define SECRET_SSID "Suites at Third"
#define SECRET_PASS "ShadowArmadillo1"